### PR TITLE
feat: add aggregate design canvas in draw.io format

### PR DESCRIPTION
**Pull request by meinjens**
I work a lot with the aggregate design canvas in diagrams.net plugin for IntelliJ (https://plugins.jetbrains.com/plugin/15635-diagrams-net-integration). So here is the V1.1 in the new format. Feel free to correct issues.

### CODE REVIEW

**Comment by meinjens** [comment]
Please review this PR. @cakper

**Comment by gabrielanhaia** [comment]
Hey @meinjens , I think there is a little adjustment to be done. There are two "description" words on the SVG (at least)

image

**Comment by cakper** [comment]
Fine with me, can you please address @gabrielanhaia comment and I will merge it? Thanks for the contribution :)

**Comment by meinjens** [comment]
@cakper @gabrielanhaia The description is removed.

**Pull request merged**
