### PR TITLE
Create "Excalidraw" diagram for the version 1.1

### PR DESCRIPTION
**Pull request by gabrielanhaia**
Create a diagram `.excalidraw` to be opened on https://excalidraw.com/

- [x] Create the diagram
- [x] Add the credits and license
- [x] Update README.md

### CODE REVIEW

**Comment by gabrielanhaia** [comment]
In the end it looks like this: 
image

**Comment by gabrielanhaia** [comment]
@cakper @NTCoding WDYT?

**Review by NouiliKh — APPROVED** [review]

**Review by NTCoding — APPROVED** [review]
Great job, thank you.

**Review by Max-Git — CHANGES_REQUESTED** [review]
Thanks @gabrielanhaia!

Could you change the footer to something like:
Aggregate Design Canvas V1.1 by Kacper Gunia & Domain-Driven Design Crew.
Excalidraw version by Gabriel Anhaia
For more information visit....

Thanks!

**Comment by gabrielanhaia** [comment]
@Max-Git Sorry; I stole the credits by mistake :D 
I fixed it now and did not add my name, as it isn't necessary.
Thanks a lot!

image

**Review by Max-Git — APPROVED** [review]
Thanks!

**Comment by cakper** [comment]
Thanks a lot everyone for their contribution! Merging :)

**Pull request merged**
